name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    container:
      image: swift:6.0.3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y libssl-dev libcurl4-openssl-dev

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

    - name: Archive build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: .build